Select month(t.created_at),t.topic,t.right_u_c_e_p,t.sub_topic,t.subco_topic,t.subject,

-- สิทธิหลักประกันสุขภาพแห่งชาติ AND คนพิการ
count(if(t.right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'UC.TIDSIDPRB',
count(if(t.right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'UC.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'UC.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'UC.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'UC.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'UC.TIDSIDPEOPLEABOARD',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'UC.TIDSIDAEKKARCHON',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'UC.TIDSIDPAKUNSANGKOM',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'UC.TIDSIDRADWISAHAKID',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'UC.TIDSIDONGKORNMAHACHON',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'UC.TIDSIDTR44',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'UC.TIDSIDTR97',
count(if(right_u_c_e_p in ('สิทธิหลักประกันสุขภาพแห่งชาติ','สิทธิหลักประกันสุขภาพแห่งชาติ (ผู้ประกันตนคนพิการ)') and t.subject = 'อื่นๆ' ,1,NULL)) 'UC.TIDSIDETC',

-- 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น'
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'LGO.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'LGO.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'LGO.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'LGO.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'LGO.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'LGO.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'LGO.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'LGO.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'LGO.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'LGO.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'LGO.TIDSIDTR44',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'LGO.TIDSIDTR97',
count(if(t.right_u_c_e_p = 'สิทธิสวัสดิการพนักงานส่วนท้องถิ่น' and t.subject = 'อื่นๆ' ,1,NULL)) 'LGO.TIDSIDETC',

-- 'สิทธิข้าราชการ'
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'SSS.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'SSS.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'SSS.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'SSS.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'SSS.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'SSS.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'SSS.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'SSS.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'SSS.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'SSS.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'SSS.TIDSIDTR44',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'SSS.TIDSIDTR97',
count(if(t.right_u_c_e_p = 'สิทธิข้าราชการ' and t.subject = 'อื่นๆ' ,1,NULL)) 'SSS.TIDSIDETC',

-- 'สิทธิประกันสังคม'
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'PAKARN.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'PAKARN.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'PAKARN.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'PAKARN.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'PAKARN.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'PAKARN.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'PAKARN.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'PAKARN.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'PAKARN.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'PAKARN.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'PAKARN.TIDSIDTR44',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'PAKARN.TIDSIDTR97',
count(if(t.right_u_c_e_p = 'สิทธิประกันสังคม' and t.subject = 'อื่นๆ' ,1,NULL)) 'PAKARN.TIDSIDETC',

-- 'สิทธิ พ.ร.บ. เฉพาะ'
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'PRB.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'PRB.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'PRB.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'PRB.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'PRB.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'PRB.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'PRB.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'PRB.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'PRB.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'PRB.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'PRB.TIDSIDTR44',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'PRB.TIDSIDTR97',
count(if(t.right_u_c_e_p = 'สิทธิ พ.ร.บ. เฉพาะ' and t.subject = 'อื่นๆ' ,1,NULL)) 'PRB.TIDSIDETC',

-- 'สิทธิรัฐวิสาหกิจ'
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'WISAHAKIED.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'WISAHAKIED.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'WISAHAKIED.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'WISAHAKIED.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'WISAHAKIED.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'WISAHAKIED.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'WISAHAKIED.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'WISAHAKIED.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'WISAHAKIED.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'WISAHAKIED.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'WISAHAKIED.TIDSIDTR44',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'WISAHAKIED.TIDSIDTR97',
count(if(t.right_u_c_e_p = 'สิทธิรัฐวิสาหกิจ' and t.subject = 'อื่นๆ' ,1,NULL)) 'WISAHAKIED.TIDSIDETC',

-- 'สิทธิหน่วยงานรัฐอื่นๆ'
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDPRB',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDTR44',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDTR97',
count(if(t.right_u_c_e_p = 'สิทธิหน่วยงานรัฐอื่น' and t.subject = 'อื่นๆ' ,1,NULL)) 'ETCGOVERNMENT.TIDSIDETC',

-- 'สิทธิองค์การมหาชน'
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'Publicorganize.TIDSIDPRB',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'Publicorganize.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'Publicorganize.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'Publicorganize.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'Publicorganize.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'Publicorganize.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'Publicorganize.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'Publicorganize.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'Publicorganize.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'Publicorganize.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'Publicorganize.TIDSIDTR44',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'Publicorganize.TIDSIDTR97',
count(if(t.right_u_c_e_p =  'สิทธิองค์การมหาชน' and t.subject = 'อื่นๆ' ,1,NULL)) 'Publicorganize.TIDSIDETC',

-- 'สิทธิครูเอกชน'
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'Teacher.TIDSIDPRB',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'Teacher.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'Teacher.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'Teacher.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'Teacher.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'Teacher.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'Teacher.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'Teacher.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'Teacher.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'Teacher.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'Teacher.TIDSIDTR44',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'Teacher.TIDSIDTR97',
count(if(t.right_u_c_e_p =  'สิทธิครูเอกชน' and t.subject = 'อื่นๆ' ,1,NULL)) 'Teacher.TIDSIDETC',

-- 'สิทธิบุคคลต่างด้าว'
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'Alien.TIDSIDPRB',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'Alien.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'Alien.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'Alien.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'Alien.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'Alien.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'Alien.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'Alien.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'Alien.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'Alien.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'Alien.TIDSIDTR44',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'Alien.TIDSIDTR97',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลต่างด้าว' and t.subject = 'อื่นๆ' ,1,NULL)) 'Alien.TIDSIDETC',

-- 'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ'
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิพรบ.เฉพาะ' ,1,NULL)) 'Problemstatus.TIDSIDPRB',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิอปท.' ,1,NULL)) 'Problemstatus.TIDSIDOPORTROR',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิข้าราชการ' ,1,NULL)) 'Problemstatus.TIDSIDKARADCHAKARN',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดกทม.)' ,1,NULL)) 'Problemstatus.TIDSIDKARADCHAKARNBKK',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิข้าราชการ (สังกัดพัทยา)' ,1,NULL)) 'Problemstatus.TIDSIDKARADCHAKARNPATTAYA',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิคนไทยในต่างประเทศ' ,1,NULL)) 'Problemstatus.TIDSIDPEOPLEABOARD',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิครูเอกชน' ,1,NULL)) 'Problemstatus.TIDSIDAEKKARCHON',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิประกันสังคม' ,1,NULL)) 'Problemstatus.TIDSIDPAKUNSANGKOM',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิรัฐวิสาหกิจ' ,1,NULL)) 'Problemstatus.TIDSIDRADWISAHAKID',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิองค์กรมหาชน' ,1,NULL)) 'Problemstatus.TIDSIDONGKORNMAHACHON',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิทร.44' ,1,NULL)) 'Problemstatus.TIDSIDTR44',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'ติดสิทธิทร.97' ,1,NULL)) 'Problemstatus.TIDSIDTR97',
count(if(t.right_u_c_e_p =  'สิทธิบุคคลผู้มีปัญหาสถานะและสิทธิ' and t.subject = 'อื่นๆ' ,1,NULL)) 'Problemstatus.TIDSIDETC'

from ticket t 
left join province pr
on t.incidprovin = pr.name
left join nhso_zone nhz			
on pr.nhso_zone_id  = nhz.id 
where 
t.created_at between $P{start_date_time} and  $P{end_date_time}
and $X{IN,nhz.name,zone_name} and
topic = 'ร้องทุกข์' and sub_topic = 'สิทธิไม่ตรงตามจริง' and subco_topic = 'สิทธิไม่ตรงตามจริง'